### ISSUE TITLE
Mod crashes on reload after newest update

### ISSUE THREAD

**Issue by Omega-Dapling** [DominicKarma/Realistic-Sky#13]
![image](https://github.com/DominicKarma/Realistic-Sky/assets/160448971/cd74ca56-4f0b-4928-8281-784a6829ae19)
This error only happens on reload, not when initially loading mods.

**Comment by milkembers** [comment]
i'm having the same issue
![dotnet_2024-04-14_17-49-15](https://github.com/DominicKarma/Realistic-Sky/assets/61429199/bd090573-9fa1-4742-94f6-5a07ea1e4b4d)

**Comment by DominicKarma** [comment]
Should be addressed now.
