### ISSUE TITLE
Background Disappearing "randomly"

### ISSUE THREAD

**Issue by Permafrozen** [DominicKarma/Realistic-Sky#5]
I am pretty sure that this isn't recreatable, because until now it happened once after 10 minutes and one time after 5. Rejoining doesn't fix it and not even starting the game new, only unloading the Realistic Sky mod. I can imagine the issue having something to do with some issue with another Mod.
Here is my Modlist if it helps:
[Modlist.txt](https://github.com/DominicKarma/Realistic-Sky/files/14527173/Modlist.txt)

Here are my logs from that session:
[2024-03-07-3.zip](https://github.com/DominicKarma/Realistic-Sky/files/14527151/2024-03-07-3.zip)

**Comment by detroo** [comment]
disable smooth lighting in fancy lighting config

**Comment by Permafrozen** [comment]
Thank you :D

**Comment by detroo** [comment]
overbright is working fine now for me as of most recent update
